name: Deploy to AWS EKS

on:
  push:
    branches:
      - "stage"
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Deployment environment'
        required: true
        default: 'stage'

jobs:
  setup:
    uses: aimlabs/github-actions/.github/workflows/gradle-setup.yml@develop
    with:
      java-version: '25'
  deploy:
    name: Deploy to AWS EKS
    needs: setup  # This ensures 'setup' completes before 'build' starts
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download init.gradle
        uses: actions/download-artifact@v4
        with:
          name: gradle-init
          path: ~/.gradle

#      - name: Set up JDK 21
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          cache: 'gradle'

      - name: Publish Packages
        run: |
          chmod +x ./gradlew ;
          export GPR_USER=${{ secrets.GPR_USER }} ;
          export GPR_KEY=${{ secrets.GPR_KEY }} ;
          
          if [ -z "${{ github.event.inputs.ENVIRONMENT }}" ] || [ "${{ github.event.inputs.ENVIRONMENT }}" == "stage" ]; then
             export ORG_GRADLE_PROJECT_deployment_tag=stage
          elif [ "${{ github.event.inputs.ENVIRONMENT }}" == "prod" ]; then
             export ORG_GRADLE_PROJECT_deployment_tag=prod
          fi
        
          ./gradlew server:copyEngines server:jib  -Porg=${{ needs.setup.outputs.ORG_NAME}};
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        #with:
        #  version: v2.26.0  # Specify desired kubectl version
      - name: Get Callers identity
        run: |
          aws sts get-caller-identity && aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}   
          echo "rollout ${{ github.event.inputs.ENVIRONMENT }}"
          if [ -z "${{ github.event.inputs.ENVIRONMENT }}" ] || [ "${{ github.event.inputs.ENVIRONMENT }}" == "stage" ]; then
            kubectl rollout restart deployment rgs-stage -n agp-stage
          elif [ "${{ github.event.inputs.ENVIRONMENT }}" == "prod" ]; then
            kubectl rollout restart deployment rgs -n agp
          fi